inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/application.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/routing/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 3

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
