dist: xenial
notifications:
  email: false

rvm:
  - 2.7.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

jdk: openjdk11

env:
  global:
    - CC_TEST_REPORTER_ID=ba2f6682d28e286af5058aa65942f43c91e20497fe2754e4beb6d8c88f30d0c6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
