version: '3'
services:
  iiif_search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    volumes:
      - ./bin:/app/bin
      - ./app:/app/app
      - ./db:/app/db
      - ./config:/app/config
      - ./public:/app/public
