iiif:
  ignored_request_params: [motivation, date, user]
  canvas_url: 'https://crkn-iiif-api.azurewebsites.net/canvas'

solr:
  url: 'http://public:hdwi389e8d!ds@4.204.49.142/solr/content_search'
  highlight_path: 'select'
  highlight_params:
    fl: 'id'
  suggest_path: 'suggest'
  suggest_params:
    'suggest.count': 1000