iiif:
  ignored_request_params: [motivation, date, user]
  canvas_url: <%= ENV.fetch('IIIF_CANVAS_URL', 'https://crkn-iiif-api.azurewebsites.net/canvas') %>

solr:
  url: <%= ENV.fetch('SOLR_URL', 'http://public:hdwi389e8d!ds@4.229.225.26/solr/content_search') %>
  highlight_path: 'select'
  highlight_params:
    df: ocrtext
    qf: ocrtext
    fl: "id,canvas_index,ocrbbox,ocrtext,score"
    hl.method: unified
    hl.fl: "ocrtext_en ocrtext_zh_hant ocrtext"
    hl.offsetSource: ANALYSIS   # analyze stored ocrtext at request time
    hl.tag.pre: "<em>"
    hl.tag.post: "</em>"
    hl.tag.ellipsis: " "
    hl.requireFieldMatch: true
    hl.snippets: 3
    hl.fragsize: 140
  suggest_path: 'suggest'
  suggest_params:
    'suggest.count': 1000